apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes'
      kubernetes_sd_configs:
      - role: node
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_name]
        action: replace
        target_label: kubernetes_node
